notifications:
  slack: eit62-tms:MF64hZ5PQK6xKhT4jW0bF2mW
language: android
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
before_install:
 - chmod +x ./src/android-app/gradlew
script:
  - ./src/android-app/gradlew build