CREATE TABLE User 
(
  ID int NOT NULL PRIMARY KEY,
  Salt TEXT NOT NULL,
  Hash TEXT NOT NULL,
  UserName TEXT NOT NULL
);

CREATE TABLE Project 
(
  ID INTEGER NOT NULL PRIMARY KEY,
  Timestamp TEXT NOT NULL,
  Description TEXT NOT NULL
);

CREATE TABLE Comment 
(
  ID INTEGER NOT NULL PRIMARY KEY,
  Timestamp TEXT,
  Text TEXT,
  IDTicket INTEGER;
);

CREATE TABLE Status
(
  ID INTEGER NOT NULL PRIMARY KEY,
  Color TEXT NOT NULL,
  Description TEXT
);

CREATE TABLE Ticket 
(
  ID INTEGER NOT NULL PRIMARY KEY,
  Timestamp TEXT NOT NULL,
  Userstory TEXT NOT NULL,
  AcceptanceCriteria TEXT NOT NULL,
  Titel TEXT NOT NULL,
  Creater INTEGER NOT NULL
  IDProjeckt INTEGER NOT NULL;
  IDStatus INTEGER NOT NULL;
);

--Hilfstabellen
CREATE TABLE ProjectMember
(
  IDUser INTEGER NOT NULL PRIMERY KEY,
  IDProjekt INTEGER NOT NULL PRIMERY KEY
);

CREATE TABLE UserComments
(
  IDUser INTEGER NOT NULL PRIMARY KEY,
  IDComment INTEGER NOT NULL PRIMARY KEY  
);

CREATE TABLE TicketEditor
(
  IDUser INTEGER NOT NULL PRIMARY KEY,
  IDTicket INTEGER NOT NULL PRIMARY KEY,
  Timestamp TEXT NOT NULL
);
